apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 3  # Number of pod replicas
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: yaeshvann/gtech:2
        ports:
        - containerPort: 8080  

---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: NodePort  
  selector:
    app: myapp  
  ports:
  - port: 8080    
    targetPort: 8080  
    nodePort: 30002  
